feat: 인증된 Member 조회 API 연동
Team-Pravo/Pravo-Client pull request #58
Opened 2024-11-20 11:17 UTC by inourbubble2

## 📝 개요
Member 조회 API 연동

## 🪐 작업 내용
- [] 최초 로그인 시, SecureStorage에 `member_id` 저장
- [] 설정 페이지 진입 시, GET /member/{memberId} API 호출
- [] 프로필 프리뷰 & 수정 위젯에서 받아온 멤버의 사진과 닉네임 노출

## 🛰️ 이슈 번호
#56

## 📚 참고 자료
![Simulator Screenshot - iPhone 15 - 2024-11-20 at 20 11 19](https://github.com/user-attachments/assets/9fd02ef4-b58b-4de9-8228-c1ad5a9f2f6c)
![Simulator Screenshot - iPhone 15 - 2024-11-20 at 20 05 29](https://github.com/user-attachments/assets/a8dcfff1-652e-4310-a67d-3a5d322368b3)

### 수정 후
![image](https://github.com/user-attachments/assets/aaf8bc98-d43d-4467-a25b-b4384c318760)

2024-11-24 06:52 UTC, gaeguul requested changes

2024-11-24 06:52 UTC, gaeguul commented on lib/features/setting/presentation/widgets/nickname_edit_widget.dart
> +          name,
이 부분은 '닉네임'으로 해야 할 것 같습니다!

2024-11-24 06:52 UTC, gaeguul commented on lib/features/member/data/models/member_model.dart
> +  Member toEntity(int memberId) {
model이 entity에 의존하는 형태인데 mapper와 같은 클래스가 필요할까요? 이 부분 어떻게 생각하시는지 궁금합니다!

2024-11-25 06:17 UTC, inourbubble2 commented on lib/features/member/data/models/member_model.dart
> +  Member toEntity(int memberId) {
저는 data -> domain 방향 의존성이니까 괜찮다고 봤어요! 그 반대 방향만 아니면 괜찮지.. 않을까요!?

2024-11-25 06:18 UTC, inourbubble2 commented on lib/features/setting/presentation/widgets/nickname_edit_widget.dart
> +          name,
수정 완료 했습니다~!

2024-11-25 06:35 UTC, gaeguul commented on lib/features/member/data/models/member_model.dart
> +  Member toEntity(int memberId) {
앗 찾아보니까 domain이 가장 독립적이고 data가 domain에 의존하도록 구현하는 거군요! 제가 반대로 생각했던 것 같습니다 ㅎㅎ

2024-11-25 06:36 UTC, gaeguul approved these changes

2024-11-25 06:36 UTC, merged